name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    environment: production  # Replace with your environment name if applicable
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Debug Environment Variables
        run: |
          echo "HF_USERNAME: $HF_USERNAME"
          echo "SPACE_NAME: $SPACE_NAME"
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: ${{ env.HF_USERNAME }}
          SPACE_NAME: ${{ env.SPACE_NAME }}
        run: git push https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME main
